### ISSUE TITLE
Feedback on mini_ex 7 by Laura Corneliussen

### ISSUE THREAD

**Issue by laurakoust** [MagnusJMJ/APME#10]
I really like your program! Its a lot of fun, but still pretty simple - and so is your code :) 
I would have liked it, if you wrote comments in your coding to describe what you are doing. That would have made it easier for me to understand your coding ;) 

Any ways its great! And really impressive that you have found some 'errors' in the dom!!! Im amazed!

**Comment by MagnusJMJ** [comment]
Thank you for the feedback. miniexercise7_+_comments.js is identical to miniexercise7.js, but has commentary code. Just wanted to clear that up. :)
