### ISSUE TITLE
Feedback on mini_ex6 by Nynne Lucca Christiansen

### ISSUE THREAD

**Issue by nynnelucca** [MagnusJMJ/APME#9]
**Impression/first thoughts:**
I really like the style of your program and the combination of the grid and the squares. It has a simplistic look which for me is preferable. It is very good that you have implemented a toggle bar as we saw Tobias had done in his code. It simply makes it look a bit more professional. You could have made the Start/stop botton either say 'start' or 'stop' depending on the program which would have given it a nice touch. Shiffman has a video on it, and I used it in my mini_ex4, so you can go check that out if you want. 
It is also really nice that you can stop the program and fill out the blanks yourself. 
I did notice that if you stop the program, press 'clear' and then run it again nothing happens. 
Nice title. 

**Your code:**
First of all it is good to see that you keep your code organised. You code is very advanced which is good. I am wondering if you made it with the help from Shiffman, and if you understand it yourself? You have a lot of comments which is also good, both for me and yourself. I am also wondering about how you made the grid. I cannot find it in your code, but I will ask you tomorrow! I want to make one myself... 

**Your rules:**
Good description. Like the fact that you have given them an anthropomorphic character. 

**Your reflections on generativity:**
It could be discussed if the subject of 'who is the author' is decided before the user comes into the picture. In a way the generativity of the program somewhat lies in the unexpectedness, but you say that it is possible to figure out the outcome beforehand? 
I recently heard that part of the pleasure of listening to music is in the surprise. The fact that we cannot quite imagine exactly what comes next when we are listening to a new song, and which is why we can get tired of songs. Maybe you can think about why we rush to judge this kind of art, often exercised through the computer, as generative and almost detached from the one who has written the code, when we do not rush to categorize magnificent and innovative the same way.

**Comment by MagnusJMJ** [comment]
Thank you for the feedback! I'm afraid I can't take credit for the name, nor the anthropomorphic undertones in the rules, but I agree with you that it's an interesting aspect of the program.

Funny thing is, there _is_ an example of how to make the Game of Life with p5.js on their website (Philip showed me). Their version is very different from mine though - namely, theirs does the same thing with half the code, and mine has some structural shortcomings that make it a lot more complex than it has to be. :v
